INSERT INTO student(uni, full_name, class_year, gpa) VALUES ('ag4219', 'Angel Garcia', 2023, 4.3333);
INSERT INTO student(uni, full_name, class_year, gpa) VALUES ('mr3986', 'Martin Ristovski', 2023, 4.3333);
INSERT INTO student(uni, full_name, class_year, gpa) VALUES ('nm1708', 'Nichoal Muro', 2023, 4.0);
INSERT INTO student(uni, full_name, class_year, gpa) VALUES ('ap0000', 'Alia Powell', 2023, 3.2);
INSERT INTO student(uni, full_name, class_year, gpa) VALUES ('gp0001', 'Gemma Price', 2022, 2.5);
INSERT INTO student(uni, full_name, class_year, gpa) VALUES ('mh0002', 'Malik Howard', 2024, 2.1);
INSERT INTO student(uni, full_name, class_year, gpa) VALUES ('ec0003', 'Ezequiel Carroll', 2023, 1.7);
INSERT INTO student(uni, full_name, class_year, gpa) VALUES ('em0004', 'Elisha Montes', 2023, 3.7);
INSERT INTO student(uni, full_name, class_year, gpa) VALUES ('ju0005', 'Joaquin Underwood', 2023, 3.6);
INSERT INTO student(uni, full_name, class_year, gpa) VALUES ('sa0006', 'Sidney Aguilar', 2023, 3.47);
INSERT INTO student(uni, full_name, class_year, gpa) VALUES ('af0007', 'Axel Fisher', 2023, 3.0);
INSERT INTO student(uni, full_name, class_year, gpa) VALUES ('aw0008', 'Akira Wagner', 2023, 3.1);

INSERT INTO major(title) VALUES ('Computer Science');
INSERT INTO major(title) VALUES ('Electrical Engineering');
INSERT INTO major(title) VALUES ('Mechanical Engineering');
INSERT INTO major(title) VALUES ('Biomedical Engineering');
INSERT INTO major(title) VALUES ('Computer Engineering');
INSERT INTO major(title) VALUES ('Applied Mathematics');
INSERT INTO major(title) VALUES ('Applied Physics');
INSERT INTO major(title) VALUES ('Film/Theatre');
INSERT INTO major(title) VALUES ('Biology');
INSERT INTO major(title) VALUES ('Biochemistry');

INSERT INTO department(name) VALUES ('Applied Physics and Applied Mathematics Department');
INSERT INTO department(name) VALUES ('Biomedical Engineering Department');
INSERT INTO department(name) VALUES ('Chemical Engineering Department');
INSERT INTO department(name) VALUES ('Civil Engineering and Engineering Mechanics Department');
INSERT INTO department(name) VALUES ('Computer Science Department');
INSERT INTO department(name) VALUES ('Earth and Environmental Engineering Department');
INSERT INTO department(name) VALUES ('Electrical Engineering Department');
INSERT INTO department(name) VALUES ('Industrial Engineering & Operations Research, Department of');
INSERT INTO department(name) VALUES ('Mechanical Engineering Department');
INSERT INTO department(name) VALUES ('Art History and Archaeology Department');

INSERT INTO school(name) VALUES ('Arts');
INSERT INTO school(name) VALUES ('Barnard College');
INSERT INTO school(name) VALUES ('Business');
INSERT INTO school(name) VALUES ('Fu Foundation School of Engineering and Applied Science');
INSERT INTO school(name) VALUES ('Public Health');
INSERT INTO school(name) VALUES ('Vagelos College of Physicians and Surgeons');
